# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: hecktor_datamodule.yaml # choose the datamodule for evaluation
  - model: hecktor_model.yaml
  - callbacks: default.yaml
  - logger: wandb
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir:  /data/datasets/TMSS_EC_Sorted/


print_config: True

ignore_warnings: True

seed: 786

name: "default"

# passing checkpoint path is necessary
ckpt_path: "/home/koung/TMSS/tmss_miccai-master/logs/experiments/runs/default/2024-08-18_22-13-52/checkpoints/epoch_011.ckpt"
